### ISSUE TITLE
No maze in the nether

### ISSUE THREAD

**Issue by emielderckx** [replaceitem/mazeworld#1]
It would be cool if the nether also would have a maze, same for the end.

**Comment by replaceitem** [comment]
Yes, this is [planned for the future](https://github.com/replaceitem/mazeworld/blob/master/src/main/java/mazeworld/mixin/WorldPresetsRegistrarMixin.java#L35-L37)

**Comment by replaceitem** [comment]
Added in 8415f977eb30a4ea42ec698c8c4b940654013d2a

**Comment by emielderckx** [comment]
Love ❤️
