### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [replaceitem/mazeworld#2]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

**Comment by replaceitem** [comment]
I have already started (and almost finished) porting some time ago, but due to changes in minecrafts registry, the nether and end dimension generation got broken with mazes. I will get back to fixing that at some point.

**Comment by replaceitem** [comment]
Those issues are now fixed in 3794cb97690c86d785b9c044671239a308ceb0ca.
1.19.3 also released to Modrinth.
